"""Add invalidated_tokens table for logout functionality

Revision ID: 6f684eed73e5
Revises: c2b7d882b174
Create Date: 2025-06-10 20:27:20.579494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f684eed73e5'
down_revision: Union[str, None] = 'c2b7d882b174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalidated_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jti_expires', 'invalidated_tokens', ['jti', 'expires_at'], unique=False)
    op.create_index(op.f('ix_invalidated_tokens_id'), 'invalidated_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_invalidated_tokens_jti'), 'invalidated_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_invalidated_tokens_user_id'), 'invalidated_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invalidated_tokens_user_id'), table_name='invalidated_tokens')
    op.drop_index(op.f('ix_invalidated_tokens_jti'), table_name='invalidated_tokens')
    op.drop_index(op.f('ix_invalidated_tokens_id'), table_name='invalidated_tokens')
    op.drop_index('idx_jti_expires', table_name='invalidated_tokens')
    op.drop_table('invalidated_tokens')
    # ### end Alembic commands ###
