"""add_hashed_password_column

Revision ID: c2b7d882b174
Revises: 987e257921db
Create Date: 2025-06-09 23:27:56.396616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b7d882b174'
down_revision: Union[str, None] = '987e257921db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index(op.f('idx_user_email'), table_name='users')
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('idx_user_google_id'), table_name='users')
    op.create_index('idx_user_google_id', 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_google_id', table_name='users')
    op.create_index(op.f('idx_user_google_id'), 'users', ['google_id'], unique=True)
    op.drop_index('idx_user_email', table_name='users')
    op.create_index(op.f('idx_user_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    # ### end Alembic commands ###
