"""fix_otp_table_schema_add_user_id_and_purpose

Revision ID: f5070496e546
Revises: 6f684eed73e5
Create Date: 2025-06-11 22:35:18.192983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5070496e546'
down_revision: Union[str, None] = '6f684eed73e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, clear any existing OTP data since we're changing the schema significantly
    op.execute("DELETE FROM otps")
    
    # Add new columns
    op.add_column('otps', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('otps', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('otps', sa.Column('purpose', sa.String(), nullable=False))
    
    # Drop the old primary key constraint on email
    op.execute("ALTER TABLE otps DROP CONSTRAINT otps_pkey")
    
    # Make email nullable and no longer primary key
    op.alter_column('otps', 'email', existing_type=sa.String(), nullable=False)
    
    # Add new primary key constraint on id
    op.execute("ALTER TABLE otps ADD PRIMARY KEY (id)")
    
    # Create indexes
    op.create_index('idx_otp_user_id', 'otps', ['user_id'], unique=False)
    op.create_index('idx_otp_user_purpose', 'otps', ['user_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    
    # Add foreign key constraint
    op.create_foreign_key(None, 'otps', 'users', ['user_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Clear any existing data since downgrading schema
    op.execute("DELETE FROM otps")
    
    # Drop foreign key and indexes first
    op.drop_constraint(None, 'otps', type_='foreignkey')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index('idx_otp_user_purpose', table_name='otps')
    op.drop_index('idx_otp_user_id', table_name='otps')
    
    # Drop the primary key constraint on id
    op.execute("ALTER TABLE otps DROP CONSTRAINT otps_pkey")
    
    # Drop new columns
    op.drop_column('otps', 'purpose')
    op.drop_column('otps', 'user_id')
    op.drop_column('otps', 'id')
    
    # Restore email as primary key
    op.execute("ALTER TABLE otps ADD PRIMARY KEY (email)")
    
    # ### end Alembic commands ###
